### ISSUE TITLE
Database conversion not possible

### ISSUE THREAD

**Issue by Fietsaapje** [pommi/python-itho-wpu#4] opened 2021-05-23 19:51 UTC
If i try to run the './convert-itho-db.py --itho-db \$_parameters_HeatPump.par' command in order to change the database to sqlite, i get the following prompt: 'Illegal instruction'. The database '$_parameters_HeatPump.par' is downloaded in the same folder.

**Comment by pommi** [comment] 2021-05-25 09:37
Hi @Fietsaapje , I'm not able to reproduce your issue. Can you share more details about your environment and the exact steps you took to get the 'Illegal instruction' error?

**Comment by Fietsaapje** [comment] 2021-05-27 21:35
I have tried to follow the instructions as closely as possible. Only thing i didn't do is start with a fresh Raspberry pi os lite image. My image is around 5 months old, but all packages are upgraded. Kernel version is 5.10.17 and debian version 10.9.

First i enabled I2C and installed all software listed. I also changed the sample rate of pigpiod and enabled the service. Next i copied the entire command listed under "Install version 0.9.0-1 of odbc-mdbtools" which download the 3 files and installed the tool. I rebooted the Pi and installed the python-itho-wpu.git files in '/home/pi/python-itho-wpu'. After that i downloaded Microsoft access database directly with command: "curl -OL "https://servicetool.blob.core.windows.net/release/Parameters/\$_parameters_HeatPump.par"
". Now when i try to run the convert script with command "./convert-itho-db.py --itho-db \$_parameters_HeatPump.par", the prompt briefly gives "Converting $_parameters_HeatPump.par to heatpump.sqlite" and then says "Illegal instruction".

I will attach an image of the exact prompt when i try to run the command.

![Illegal instruction](https://user-images.githubusercontent.com/62953026/119899851-ff304680-bf43-11eb-9ad6-3b9f385c6a93.PNG)

Is it maybe possible for you to somehow upload the converted database?

**Comment by Fietsaapje** [comment] 2021-05-27 21:44
This is what the prompt says when i try to install odbc-mdbtools. It seems to stop at 'processing triggers' Is this supposed to happen?

![install odbc-mdbtools](https://user-images.githubusercontent.com/62953026/119900807-4ff46f00-bf45-11eb-857b-604aa18db75e.PNG)

**Comment by pommi** [comment] 2021-05-30 11:47
Interesting. I'm still not able to reproduce it :disappointed: After 'processing triggers' the packages are successfully installed, so that's good.

The good news is that the issue I had with mdbtools from Buster/Bullseye seems to be fixed in mdbtools 0.9.3-1, available in Debian Unstable. [I've updated the README](https://github.com/pommi/python-itho-wpu/commit/153da73b085c5c280dc55834e24d0053c6f508e7). Could you try it again with 0.9.3-1?

**Comment by pommi** [comment] 2021-05-30 11:55
One more thing: https://github.com/pommi/python-itho-wpu/commit/8c7d0ed94721834f8049c1624e61945b701c9280

mdbtools 0.9.3-1 can't handle filename `$_parameters_HeatPump.par`, so save it as HeatPump.par

**Comment by Fietsaapje** [comment] 2021-05-31 21:50
Thanks for trying to help me, however i'm getting the exact same 'illegal instruction' error after installing mbdtools 0.9.3-1 and re-cloning the git. I forgot to mention i'm running on a Raspberry Pi Zero W. This might be part of the problem. I think the only thing left for me to try is to start with a fresh image and/or use a regular Pi model and see what happens.

**Comment by EJhagenaar** [comment] 2021-06-07 12:43
> Thanks for trying to help me, however i'm getting the exact same 'illegal instruction' error after installing mbdtools 0.9.3-1 and re-cloning the git. I forgot to mention i'm running on a Raspberry Pi Zero W. This might be part of the problem. I think the only thing left for me to try is to start with a fresh image and/or use a regular Pi model and see what happens.

Did you solve the issue? because i am having the same issue (also running on a Raspberry Pi Zero W)
![image](https://user-images.githubusercontent.com/69298881/121018356-a0b66400-c79e-11eb-8062-20b39393f895.png)


edit: changed to rpi 3b and it works, have some other issues tho

**Comment by Fietsaapje** [comment] 2021-06-07 19:57
@EJhagenaar I just managed to get it working on the Pi Zero W! I couldn't get the conversion script to run, but i worked around it by running the conversion script on a Pi 3B and copying the generated 'heatpump.sqlite' file to the 'python-itho-wpu' directory of the Pi Zero W. 

I found that if you have SSH enabled on both Pi's you can easily copy the file to the Pi Zero by running the following command on the Pi 3B:  "scp /home/pi/python-itho-wpu/heatpump.sqlite pi@192.168.2.70:/home/pi/". Obviously you have to change the IP to your Pi Zero's IP. I copied the file to "home/pi/" and then used "mv heatpump.sqlite python-itho-wpu" because of permission issues when directly copying to the python-itho-wpu directory.

If you have any further questions i might be able to help you. And @pommi maybe it is an idea to include the converted database in the Git? Eitherway thanks for the software because it seems to be doing it's job after the conversion issue has been resolved.

**Comment by EJhagenaar** [comment] 2021-06-08 09:20
@Fietsaapje I just inserted the sd card in to the pi 3b and executed the script. when the script finished i just put the sd card back in to the zero.

only thing left is:
![image](https://user-images.githubusercontent.com/69298881/121159136-38718c00-c84b-11eb-9551-6caac1ad7ef5.png)
i trying to figure it out but until now no success

changed the credentials in the export.py and now it works

for the pi zero it is also important to take the correct version of grafana:
```
sudo apt-get install -y adduser libfontconfig1
wget https://dl.grafana.com/oss/release/grafana-rpi_8.0.0_armhf.deb
sudo dpkg -i grafana-rpi_8.0.0_armhf.deb
```

**Closed as completed** 2021-06-14 11:32 UTC
